name: Python Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run simple script
        run: echo "Hello GitHub Actions! Python is ready."
          - name: Create sample file
    run: echo "Test artifact" > output.txt

  - name: Upload artifact
    uses: actions/upload-artifact@v3
    with:
      name: my-artifact
      path: output.txt



