      - name: Create sample artifact file
        run: echo "Test artifact" > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output.txt
